[project]
name = "morfometria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
    "pyside6>=6.9.0",
]
